version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      laverve:
        applies-to: version-updates
        patterns:
          - "@laverve*"
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook*"
      react:
        applies-to: version-updates
        patterns:
          - "react*"
          - "*react"
          - "*react*"
      fusion:
        applies-to: version-updates
        patterns:
          - "matter-js"
          - "*matter-js"
          - "pixi.js"
          - "@pixi/"
      uncategorized:
        applies-to: version-updates
        patterns:
          - "*"